### ISSUE TITLE
Cron task error

### ISSUE THREAD

**Issue by Binnette** [YunoHost-Apps/selfoss_ynh#15]
Hi @ericgaspar,

I finally have more time to test selfoss on my Yunohost server. And since 1 year I installed it on my server, I saw that Selfoss was never updating its feed.

So I tried to run the cron task available in the file `/etc/cron.d/selfoss`

`*/15 * * * * selfoss /usr/bin/php8.0 /var/www/selfoss/cliupdate.php >>/var/log/selfoss_update.log > /dev/null`

So I ran `/usr/bin/php8.0 /var/www/selfoss/cliupdate.php` and get this error:

`Using SQLite database requires pdo_sqlite PHP extension. Please make sure you have it installed and enabled.root@binnette:/etc/cron.d#`  

I installed sqlite : `apt-get install php8.0-sqlite3`

Now sqlite seems to be loaded in php8.0:
```
php8.0 -m | grep sqlite
pdo_sqlite
sqlite3
```

Also the command `/usr/bin/php8.0 /var/www/selfoss/cliupdate.php` no longer return an error.

Now I have to wait 15mn and see if Selfoss refresh its article 😇

**Comment by ericgaspar** [comment]
What version have you been using? Selfoss has been updated with php8.2-sqlite3 for some time now.

**Comment by Binnette** [comment]
`Installed version: 2.19~ynh2`. To be sure I will uninstall it and reinstall by using Yunohost interface.

**Comment by Binnette** [comment]
Ok I reinstalled selfoss. So now I have an updated crond.d file:
```
*/15 * * * * selfoss /usr/bin/php8.2 /var/www/selfoss/cliupdate.php >>/var/log/selfoss_update.log > /dev/null
```

But the articles in selfoss are still not updated. And in fact this cron command is incorrect because user selfoss can not create and write in the file /var/log/selfoss_update.log 

To be sure I created a new cron file:
```
*/1 * * * * selfoss /usr/bin/echo tata >>/var/log/selfoss_update.log
*/1 * * * * root /usr/bin/echo toto >>/var/log/selfoss_update.log
```

So every minutes, user selfoss should write tata in the file and the root user should write toto.

After some minutes, here is the content of selfoss_update.log

```
toto
toto
toto
```

So only user root have write acces on this file.

**Comment by Binnette** [comment]
I ran this command:

` sudo -u selfoss /usr/bin/php8.2 /var/www/selfoss/cliupdate.php`

And the articles were correctly refreshed in Selfoss. So there is still an issue with the default cron file installed by Yunohost:
```
*/15 * * * * selfoss /usr/bin/php8.2 /var/www/selfoss/cliupdate.php >>/var/log/selfoss_update.log > /dev/null
```

Here is my change to write in the selfoss folder:
```
*/15 * * * * selfoss /usr/bin/php8.2 /var/www/selfoss/cliupdate.php >> /var/www/selfoss/data/logs/cliupdate.log
```

**Comment by Binnette** [comment]
Hi @ericgaspar, thanks a lot for your PR. I installed new version and now the cron task seems correct to me:
```
*/15 * * * * selfoss /usr/bin/php8.2 /var/www/selfoss/cliupdate.php >> /var/www/selfoss/data/logs/cliupdate.log
```

TY ❤️
