### ISSUE TITLE
selfoss refuses to install

### ISSUE THREAD

**Issue by Binnette** [YunoHost-Apps/selfoss_ynh#2]
Hello @ericgaspar,

Thanks a lot for your work on selfoss ❤

I can not help you diagnose your JSON.parse error for now, since your package refuses to install on my Yunohost instance.

![image](https://user-images.githubusercontent.com/6597721/159530663-1c0356bf-8609-450f-8abb-95b9af94b964.png)

Can you please consider, add a parameter in the install to allow installation in a subfolder please? (your previous package of january is asking for this subfolder)

If not possible for now:
- please consider having a look to selfoss logs directly in the installation folder.
- may be you can create a test account on your yunohost and allow me to use your selfoss. Maybe I can help you understand your JSON.Parse issue.
- or may be it exists a way to create a local Yunohost sandbox? (I don't want to remove all the app on my Yunohost just to install selfoss)

Have a nice day. Hope we can make it work 🚀

**Comment by farvardin** [comment]
@Binnette if you're using a nohost.me domain, you won't be able to configure un subdomain. You should use a dedicated domain for yunohost, and create a subdomain for selfoss.

I'm not sure selfoss can install in a subfolder.

**Comment by Binnette** [comment]
Hi @farvardin thank for your message :+1: 
According the [documentation](https://github.com/fossar/selfoss/wiki/nginx-configuration) it should be possible to install selfoss in a subfolder like /selfoss

**Comment by Binnette** [comment]
Hi @farvardin, @ericgaspar. I get selfoss to work in a subfolder. Please review my changes here: https://github.com/YunoHost-Apps/selfoss_ynh/pull/3
